name: Windows
on: 
  push:
    paths:
      - '*.txt'
      - 'src/**'
      - 'example/**'
      - 'scripts/**'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - '*.txt'
      - 'example/**'
      - 'src/**'
      - 'scripts/**'
      - '.github/workflows/windows.yml'
      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        include:
          - qt_ver: 6.5.0        
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64  
    env:
      targetName: example.exe
      fileName: example
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: inno setup install
        uses: zhuzichu520/inno-setup-action@v1.0.0
        with:
          filepath: ./InstallerScript.iss
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bin/example.exe
          asset_name: example.exe
          tag: ${{ github.ref }}
          overwrite: true 